version: "3.8"

services:
  wig_stick:
    build: .
    container_name: Stable-Hair
    ports:
      - "8986:8986"
    volumes:
      - ./Stable-Hair:/app
    environment:
      - CUDA_HOME=/usr/local/cuda
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    runtime: nvidia